
package ssiid.visa;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "VisaDAOWSService", targetNamespace = "http://dao.visa.ssii2/", wsdlLocation = "http://10.7.13.1:8080/P1-ws-ws/VisaDAOWSService?wsdl")
public class VisaDAOWSService
    extends Service
{

    private final static URL VISADAOWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException VISADAOWSSERVICE_EXCEPTION;
    private final static QName VISADAOWSSERVICE_QNAME = new QName("http://dao.visa.ssii2/", "VisaDAOWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.7.13.1:8080/P1-ws-ws/VisaDAOWSService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VISADAOWSSERVICE_WSDL_LOCATION = url;
        VISADAOWSSERVICE_EXCEPTION = e;
    }

    public VisaDAOWSService() {
        super(__getWsdlLocation(), VISADAOWSSERVICE_QNAME);
    }

    public VisaDAOWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VISADAOWSSERVICE_QNAME, features);
    }

    public VisaDAOWSService(URL wsdlLocation) {
        super(wsdlLocation, VISADAOWSSERVICE_QNAME);
    }

    public VisaDAOWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VISADAOWSSERVICE_QNAME, features);
    }

    public VisaDAOWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VisaDAOWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns VisaDAOWS
     */
    @WebEndpoint(name = "VisaDAOWSPort")
    public VisaDAOWS getVisaDAOWSPort() {
        return super.getPort(new QName("http://dao.visa.ssii2/", "VisaDAOWSPort"), VisaDAOWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VisaDAOWS
     */
    @WebEndpoint(name = "VisaDAOWSPort")
    public VisaDAOWS getVisaDAOWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dao.visa.ssii2/", "VisaDAOWSPort"), VisaDAOWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VISADAOWSSERVICE_EXCEPTION!= null) {
            throw VISADAOWSSERVICE_EXCEPTION;
        }
        return VISADAOWSSERVICE_WSDL_LOCATION;
    }

}
