
package ssiid.visa;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VisaDAOWS", targetNamespace = "http://dao.visa.ssii2/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VisaDAOWS {


    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isDebug", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.IsDebug")
    @ResponseWrapper(localName = "isDebugResponse", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.IsDebugResponse")
    @Action(input = "http://dao.visa.ssii2/VisaDAOWS/isDebugRequest", output = "http://dao.visa.ssii2/VisaDAOWS/isDebugResponse")
    public boolean isDebug();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setDebug", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.SetDebug")
    @ResponseWrapper(localName = "setDebugResponse", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.SetDebugResponse")
    @Action(input = "http://dao.visa.ssii2/VisaDAOWS/setDebugRequest", output = "http://dao.visa.ssii2/VisaDAOWS/setDebugResponse")
    public void setDebug(
        @WebParam(name = "arg0", targetNamespace = "")
        boolean arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delPagos", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.DelPagos")
    @ResponseWrapper(localName = "delPagosResponse", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.DelPagosResponse")
    @Action(input = "http://dao.visa.ssii2/VisaDAOWS/delPagosRequest", output = "http://dao.visa.ssii2/VisaDAOWS/delPagosResponse")
    public int delPagos(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isDirectConnection", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.IsDirectConnection")
    @ResponseWrapper(localName = "isDirectConnectionResponse", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.IsDirectConnectionResponse")
    @Action(input = "http://dao.visa.ssii2/VisaDAOWS/isDirectConnectionRequest", output = "http://dao.visa.ssii2/VisaDAOWS/isDirectConnectionResponse")
    public boolean isDirectConnection();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<ssiid.visa.PagoBean>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPagos", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.GetPagos")
    @ResponseWrapper(localName = "getPagosResponse", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.GetPagosResponse")
    @Action(input = "http://dao.visa.ssii2/VisaDAOWS/getPagosRequest", output = "http://dao.visa.ssii2/VisaDAOWS/getPagosResponse")
    public List<PagoBean> getPagos(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "errorLog", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.ErrorLog")
    @ResponseWrapper(localName = "errorLogResponse", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.ErrorLogResponse")
    @Action(input = "http://dao.visa.ssii2/VisaDAOWS/errorLogRequest", output = "http://dao.visa.ssii2/VisaDAOWS/errorLogResponse")
    public void errorLog(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isPrepared", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.IsPrepared")
    @ResponseWrapper(localName = "isPreparedResponse", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.IsPreparedResponse")
    @Action(input = "http://dao.visa.ssii2/VisaDAOWS/isPreparedRequest", output = "http://dao.visa.ssii2/VisaDAOWS/isPreparedResponse")
    public boolean isPrepared();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setPrepared", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.SetPrepared")
    @ResponseWrapper(localName = "setPreparedResponse", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.SetPreparedResponse")
    @Action(input = "http://dao.visa.ssii2/VisaDAOWS/setPreparedRequest", output = "http://dao.visa.ssii2/VisaDAOWS/setPreparedResponse")
    public void setPrepared(
        @WebParam(name = "arg0", targetNamespace = "")
        boolean arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "compruebaTarjeta", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.CompruebaTarjeta")
    @ResponseWrapper(localName = "compruebaTarjetaResponse", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.CompruebaTarjetaResponse")
    @Action(input = "http://dao.visa.ssii2/VisaDAOWS/compruebaTarjetaRequest", output = "http://dao.visa.ssii2/VisaDAOWS/compruebaTarjetaResponse")
    public boolean compruebaTarjeta(
        @WebParam(name = "arg0", targetNamespace = "")
        TarjetaBean arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns ssiid.visa.PagoBean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "realizaPago", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.RealizaPago")
    @ResponseWrapper(localName = "realizaPagoResponse", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.RealizaPagoResponse")
    @Action(input = "http://dao.visa.ssii2/VisaDAOWS/realizaPagoRequest", output = "http://dao.visa.ssii2/VisaDAOWS/realizaPagoResponse")
    public PagoBean realizaPago(
        @WebParam(name = "arg0", targetNamespace = "")
        PagoBean arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setDirectConnection", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.SetDirectConnection")
    @ResponseWrapper(localName = "setDirectConnectionResponse", targetNamespace = "http://dao.visa.ssii2/", className = "ssiid.visa.SetDirectConnectionResponse")
    @Action(input = "http://dao.visa.ssii2/VisaDAOWS/setDirectConnectionRequest", output = "http://dao.visa.ssii2/VisaDAOWS/setDirectConnectionResponse")
    public void setDirectConnection(
        @WebParam(name = "arg0", targetNamespace = "")
        boolean arg0);

}
